# Nixpacks 配置 - 告诉 Railway 如何构建后端项目

[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['npm ci --prefix backend --prefer-offline --no-audit']

[phases.build]
cmds = []

[start]
cmd = 'npm run dev --prefix backend'
