# Railway 部署配置
# 指定后端代码目录

[build]
builder = "NIXPACKS"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm run dev"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
